<a href="https://colab.research.google.com/github/decoz/mlclass/blob/master/2021_%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5_%EA%B8%B0%EB%A7%90%EA%B3%A0%EC%82%AC_A%EB%B0%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 2021 학년도 인공지능 기말고사 (A반)



#### 푸시기 전에 .. 

```
#### 중간고사 규칙:
- 중간고사는 오픈북 형태로서 수업시간 자료와 외부 자료를 모두 조회, 참고 가능합니다. 
- 인터넷 검색도 가능하지만 타인과의 정보교환은 엄격히 금합니다. 적발시 바로 부정행위로 조치합니다. 
- 수험 시간은 시작 이후 1시간 20분까지입니다. 
- 점수는 작성하신 프로그램중에 가장 난이도가 높은 프로그램으로 반영됩니다. 그러므로 가장 난이도가 높은 프로그램 하나만 정확히 작성하셔도 만점입니다. 
- 쉬운 프로그램을 채점 받은 후에 다시 난이도 높은 프로그램을 재 채점 받으셔도 됩니다.
```

<br>

다음은 편의를 위해 제공되는 문제에 사용되는 라이브러리들의 import 구문입니다. 


In [1]:
import numpy as np 
import torch as tc
import torch.nn as nn 
import torch.optim as optim
import matplotlib.pyplot as plt 
import pandas as pd 



<Br><Br>

---

#### 문제 1: 

0부터 99 까지 홀수와 짝수가 2열로 배치된 텐서를 생성하고 출력하세요  [30점]

출력 :
```
tensor([[ 1,  0],
        [ 3,  2],
        [ 5,  4],
        ...
        [99, 98]])

```

In [ ]:
#위와 같은 출력이 나올 수 있도록 코드를 작성하세요



<Br><Br><Br>

---
#### 문제 2:
pytorch 에서 다음의  입력 x 에 대해 출력 y 를 mse 0.1 이내로 학습하는 신경망을 작성하고 오차값을 그래프로 출력하세요   [45점]


In [10]:

xn = np.array([[0],[1],[2],[3],[4],[5],[6],[7],[8],[9]])
yn = np.array([ 
      [-4.027047  ],
      [ 5.98710915],
      [15.96500401],
      [25.93952224],
      [35.90297576],
      [45.775711  ],
      [56.05035573],
      [66.07052376],
      [75.98303501],
      [85.96016033]])

x = tc.FloatTensor(xn)
y = tc.FloatTensor(yn)

## 위의 데이터를 학습하는 신경망을 작성하세요




In [8]:

xn = np.array([[0],[1],[2],[3],[4],[5],[6],[7],[8],[9]])
yn = xn * 10 - 4 + np.random.normal(0,0.1,10).reshape(-1,1)
yn.reshape(-1,1)

array([[-4.027047  ],
       [ 5.98710915],
       [15.96500401],
       [25.93952224],
       [35.90297576],
       [45.775711  ],
       [56.05035573],
       [66.07052376],
       [75.98303501],
       [85.96016033]])



<Br><Br><Br>

---
#### 문제 3:
다음 pandas 로 읽은 데이터에서 화요일 (day of the week = 2 ) 의   'Banking orders (1)' 의 데이터를 그래프를 그래보세요 [40점]



In [ ]:
import pandas as pd
import torch as tc

df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00409/Daily_Demand_Forecasting_Orders.csv', sep = ';')
df




<Br><Br><Br>

---
#### 문제 4:
pytorch 에서 다음 x,y 를 학습해서 모델의 출력값의 반올림이 y값과 동일하도록  만드세요 [50점]

출력코드 예:
```
print( np.round(o.detach().numpy()) )
->
[[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]]


In [ ]:
xn = np.array( [[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]] )
yn = np.array( [[1],[0],[1],[0],[1],[0],[1],[0]] )

## 위의 데이터를 학습하는 신경망을 작성하세요



# 출력코드
print( np.round(o.detach().numpy()) )



<Br><Br><Br>

---
#### 문제 5:  

2진수 3자리를 10진수로 변환할 수 있도록 학습시켜 torch 를 사용해 신경망을 구성하고 학습시켜보세요  [60점]

```
[0,0,1] -> 1
[1,0,1] -> 5
[1,1,1] -> 7
```
모델 테스트 예:
```
tx = tc.FlaotTensor([1,0,1])
print( model(tx).argmax() )
-> 
tensor(5)
```


In [67]:
# 2진수 입력과 10진수 출력
x = tc.FloatTensor( [[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]] )
y = tc.tensor( [[0],[1],[2],[3],[4],[5],[6],[7]] ).view(-1,)

# 위의 케이스를 학습할 수 있는 신경망을 구성해 학습시켜보세요




### 아래 테스트 코드의 입력을 바꾸며 테스트해보세요
tx = tc.FloatTensor([1,1,1])
print( model(tx).argmax() )



tensor(7)
